Draft: Rework parameterization of CORL algorithms
gierle/CORL pull request #3
Opened 2024-09-19 13:33 UTC by Bronzila

With this PR we aim to streamline the parameterization of the CORL agents to ensure easier usage in our experiments

2024-09-19 13:33 UTC, Bronzila commented
Currently still ongoing, but feel free to leave intermediary feedback :)

2024-09-26 12:38 UTC, gierle requested changes

2024-09-26 12:38 UTC, gierle commented on algorithms/offline/sac_n.py
> -                        activation(),
Need to instantiate ReLU

2024-09-26 12:38 UTC, gierle commented on algorithms/offline/sac_n.py
> -                activation(),
same here

2024-09-26 12:38 UTC, gierle commented on algorithms/offline/sac_n.py
> +                nn.ReLU,
same here

2024-09-26 12:39 UTC, gierle commented on algorithms/offline/sac_n.py
> +                        nn.ReLU,
Need to instantiate ReLU

2024-09-30 11:15 UTC, merged